server:
  port: 8443
  ssl:
    key-store: src/main/resources/keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

firebase:
  database:
    url: https://sample-57edd.firebaseio.com/
#    url: https://<DATABASE_NAME>.firebaseio.com/
